name: Package for browsers

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-chrome:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          npm run package:chrome
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: chrome
          path: public

  build-firefox:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          npm run package:firefox
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: firefox
          path: public
