name: Package for browser

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Build
        run: |
          npm ci
          npm run package
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: assets-for-download
          path: web-ext-artifacts/*.zip
