name: Package for browsers

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_call:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: npm

      - name: build & package
        run: |
          npm ci
          npm run package

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: summer-web-clipper
          path: build/*
